### ISSUE TITLE
为全站HTML界面设定默认字体

### ISSUE THREAD

**Issue by wifi-left** [HMCL-dev/HMCL-docs#112]
为全站HTML界面设定默认字体
https://github.com/HMCL-dev/HMCL/issues/3016
可能可以解决？
比如GitHub在HTML的body中添加了：
```css
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
```

**Comment by iBug** [comment]
隔壁 @zkitefly 提到了这个 issue，我就贴一下处理方法：

创建 `assets/css/main.scss`：

```scss
---
# Only the main Sass file needs front matter (the dashes are enough)
search: false
---

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials
```

在 `@charset` 后面加入一行新的内容：

```scss
$sans-serif: // 你们想要的 font-family 列表
```

即可。
